USE [master]
GO
/****** Object:  Database [Coldrun]    Script Date: 04.02.2024 20:16:38 ******/
CREATE DATABASE [Coldrun]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Coldrun', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Coldrun.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Coldrun_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Coldrun_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [Coldrun] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Coldrun].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Coldrun] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Coldrun] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Coldrun] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Coldrun] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Coldrun] SET ARITHABORT OFF 
GO
ALTER DATABASE [Coldrun] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Coldrun] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Coldrun] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Coldrun] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Coldrun] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Coldrun] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Coldrun] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Coldrun] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Coldrun] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Coldrun] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Coldrun] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Coldrun] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Coldrun] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Coldrun] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Coldrun] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Coldrun] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Coldrun] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Coldrun] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Coldrun] SET  MULTI_USER 
GO
ALTER DATABASE [Coldrun] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Coldrun] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Coldrun] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Coldrun] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Coldrun] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Coldrun] SET QUERY_STORE = OFF
GO
USE [Coldrun]
GO
/****** Object:  Table [dbo].[Trucks]    Script Date: 04.02.2024 20:16:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Trucks](
	[Code] [nvarchar](25) NOT NULL,
	[Name] [nvarchar](max) NOT NULL,
	[Status] [int] NOT NULL,
	[Description] [nvarchar](max) NULL,
 CONSTRAINT [PK_Trucks] PRIMARY KEY CLUSTERED 
(
	[Code] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
INSERT [dbo].[Trucks] ([Code], [Name], [Status], [Description]) VALUES (N'code1', N'name', 1, N'test description')
GO
INSERT [dbo].[Trucks] ([Code], [Name], [Status], [Description]) VALUES (N'code2', N'supertruck', 1, NULL)
GO
INSERT [dbo].[Trucks] ([Code], [Name], [Status], [Description]) VALUES (N'code3', N'test', 4, N'test')
GO
INSERT [dbo].[Trucks] ([Code], [Name], [Status], [Description]) VALUES (N'test', N'name', 3, NULL)
GO
INSERT [dbo].[Trucks] ([Code], [Name], [Status], [Description]) VALUES (N'test2', N'name2', 2, N'')
GO
USE [master]
GO
ALTER DATABASE [Coldrun] SET  READ_WRITE 
GO
